# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Inocar Controller' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Inocar Controller
  pod 'RxSwift'
  pod 'RxBluetoothKit'
  pod 'CDJoystick'
  post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'RxBluetoothKit' || target.name == 'RxSwift'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '5.1'
            end
        end
    end
  end
end
